"use client";

import { ArrowsClockwise, Lightning, Shield, Sword, Trophy } from "@phosphor-icons/react";
import { AnimatePresence, motion } from "framer-motion";
import { MOVES, multiplier } from "@/lib/battle/engine";
import { getPokemonArtwork } from "@/lib/battle/pokemon";
import { pokemonData } from "@/helpers/PokemonTypes";

const iconFor = { strike: Sword, "type-strike": Lightning };
const colorFor = (type) => pokemonData.find((item) => item.type === type)?.color || "#64748b";

function HpBar({ pokemon }) { const percent = Math.max(0, pokemon.hp / pokemon.maxHp * 100); return <div className="hp-wrap"><div className="hp-label"><span>HP</span><strong>{pokemon.hp}/{pokemon.maxHp}</strong></div><div className="hp-track"><motion.div className={`hp-fill ${percent < 35 ? "danger" : ""}`} animate={{ width: `${percent}%` }} /></div></div>; }

function Fighter({ side, player, active, isHit }) { const pokemon = player.team[player.active]; return <div className={`combatant ${side} ${isHit ? "is-hit" : ""}`}><div className="combatant-copy"><span className="combatant-label">{player.name}</span><h2>{pokemon.name}</h2><div className="type-pill" style={{ backgroundColor: colorFor(pokemon.type) }}>{pokemon.type}</div><HpBar pokemon={pokemon} /></div><motion.img animate={{ y: [0, -4, 0] }} transition={{ repeat: Infinity, duration: side === "player" ? 2.4 : 2.8 }} src={getPokemonArtwork(pokemon)} alt={pokemon.name} /></div>; }

export default function BattleArena({ state, role, onAction, onRematch }) {
  const me = state[role]; const opponentRole = role === "host" ? "guest" : "host"; const opponent = state[opponentRole];
  const myTurn = state.turn === role && state.status === "playing"; const effect = state.effect; const isHit = effect?.target === role;
  const active = me.team[me.active]; const enemy = opponent.team[opponent.active];
  const turnLabel = state.status === "countdown" ? "3 · 2 · 1 · BATALHA!" : state.status === "finished" ? "BATALHA ENCERRADA" : myTurn ? "⚡ SUA VEZ!" : `AGUARDANDO ${opponent.name.toUpperCase()}...`;
  return <><section className={`battle-arena ${myTurn ? "my-turn" : "waiting-turn"}`} aria-label="Arena de batalha"><div className="turn-banner" role="status" aria-live="polite">{turnLabel}</div><Fighter side="opponent" player={opponent} isHit={effect?.target === opponentRole} /><div className="versus"><span>VS</span></div><Fighter side="player" player={me} isHit={isHit} /><AnimatePresence>{effect?.kind === "attack" && <motion.div className={`attack-effect type-${effect.type}`} initial={{ opacity: 0, scale: .4 }} animate={{ opacity: 1, scale: 1.15 }} exit={{ opacity: 0 }}><span>{effect.effective ? "★" : "✦"}</span><strong>-{effect.damage}</strong></motion.div>}</AnimatePresence><div className={`battle-message ${effect?.effective ? "is-strong" : ""}`} role="status" aria-live="polite">{state.log}</div></section><section className={`battle-controls ${myTurn ? "is-active" : ""}`}><div className="controls-heading"><div><span className="eyebrow">{myTurn ? "ESCOLHA AGORA" : "BATALHA EM CURSO"}</span><h2>{myTurn ? "Escolha uma ação" : "Espere sua vez"}</h2></div><span className="team-left"><Shield size={18} /> {me.team.filter((pokemon) => pokemon.hp > 0).length} na equipe</span></div><div className="attack-grid">{MOVES.map((move) => { const Icon = iconFor[move.id]; const attackType = move.type === "own" ? active.type : move.type; const strong = multiplier(attackType, enemy.type) > 1; return <button type="button" key={move.id} className={`attack-button ${strong ? "recommended" : ""}`} disabled={!myTurn} onClick={() => onAction({ type: "attack", moveId: move.id })}><span className="attack-icon"><Icon size={25} weight="fill" /></span><span><strong>{move.type === "own" ? `Golpe ${active.type}` : move.name}</strong>{strong && <small>Super efetivo</small>}</span></button>; })}</div><div className="switch-row"><span>Trocar Pokémon</span><div className="reserve-list">{me.team.map((pokemon, index) => <button type="button" key={`${pokemon.id}-${index}`} className={index === me.active ? "selected" : ""} disabled={!myTurn || pokemon.hp <= 0 || index === me.active} onClick={() => onAction({ type: "switch", index })} aria-label={`Usar ${pokemon.name}`}><img src={getPokemonArtwork(pokemon)} alt="" /><span>{pokemon.name}</span></button>)}</div></div></section><AnimatePresence>{state.status === "finished" && <motion.div className="result-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><motion.div className="result-card" initial={{ scale: .8, y: 20 }} animate={{ scale: 1, y: 0 }}><Trophy size={42} weight="fill" /><span className="eyebrow">{state.winner === role ? "VOCÊ VENCEU" : "BOA BATALHA"}</span><h2>{state.winner === role ? "Vitória!" : "Tente novamente"}</h2><p>{state.winner === role ? `${me.name} venceu esta batalha.` : `${opponent.name} venceu desta vez.`}</p><button type="button" className="rematch-button" onClick={onRematch}><ArrowsClockwise size={20} /> Pedir revanche</button></motion.div></motion.div>}</AnimatePresence></>;
}
