// Framework-free battle domain. The host resolves this state for CPU and online matches.
const ADVANTAGES = { electric: ["water", "flying"], water: ["fire", "ground", "rock"], fire: ["grass", "ice", "bug", "steel"], grass: ["water", "ground", "rock"], fighting: ["normal", "rock", "steel", "ice", "dark"], ground: ["fire", "electric", "poison", "rock", "steel"], psychic: ["fighting", "poison"], ice: ["grass", "ground", "flying", "dragon"], dark: ["psychic", "ghost"], ghost: ["psychic", "ghost"], fairy: ["fighting", "dragon", "dark"], rock: ["fire", "ice", "flying", "bug"], flying: ["grass", "fighting", "bug"], poison: ["grass", "fairy"], bug: ["grass", "psychic", "dark"], steel: ["ice", "rock", "fairy"], dragon: ["dragon"] };

export const MAX_SPECIAL_ATTACK_USES = 2;
export const MAX_POTIONS = 2;
export const MAX_HEALS_PER_POKEMON = 3;
export const POTION_HEAL_PERCENTAGE = .4;
export const STATUS_DAMAGE_PERCENTAGE = .08;
export const BATTLE_BAG = Object.freeze({ potion: { id: "potion", name: "Poção", quantity: 2, description: "Recupera 40% do HP" }, "full-heal": { id: "full-heal", name: "Cura Total", quantity: 1, description: "Remove um estado" } });
export const DAMAGE_BALANCE = Object.freeze({ SUPER_EFFECTIVE: 1.3, DOUBLE_WEAKNESS_CAP: 1.5, RESISTED: .75, STAB: 1.1, MIN_ATTACK_RATIO: .65, MAX_ATTACK_RATIO: 1.55, REGULAR_MIN: .06, REGULAR_MAX: .35, SPECIAL_MIN: .10, SPECIAL_MAX: .45, VARIANCE: .05 });

const TYPE_MOVES = { normal: ["Tackle", "Quick Attack", "Hyper Beam"], fire: ["Ember", "Fire Fang", "Flamethrower"], water: ["Water Gun", "Aqua Tail", "Hydro Pump"], grass: ["Vine Whip", "Razor Leaf", "Solar Beam"], electric: ["Thunder Shock", "Spark", "Thunderbolt"], ice: ["Powder Snow", "Ice Fang", "Ice Beam"], fighting: ["Karate Chop", "Brick Break", "Close Combat"], poison: ["Poison Sting", "Acid", "Sludge Bomb"], ground: ["Mud-Slap", "Bulldoze", "Earthquake"], flying: ["Peck", "Wing Attack", "Air Slash"], psychic: ["Confusion", "Psybeam", "Psychic"], bug: ["Bug Bite", "X-Scissor", "Bug Buzz"], rock: ["Rock Throw", "Rock Slide", "Stone Edge"], ghost: ["Astonish", "Shadow Sneak", "Shadow Ball"], dragon: ["Dragon Breath", "Dragon Claw", "Dragon Pulse"], dark: ["Bite", "Assurance", "Dark Pulse"], steel: ["Metal Claw", "Iron Head", "Flash Cannon"], fairy: ["Fairy Wind", "Draining Kiss", "Moonblast"] };
const STATUS_BY_TYPE = { fire: "burn", poison: "poison", electric: "paralysis", ice: "sleep", grass: "sleep" };
// Held-item behavior belongs to the battle domain. UI components render only
// structured results and never decide whether an item may activate.
export const HELD_ITEM_TRIGGER = Object.freeze({ AFTER_DAMAGE_RECEIVED: "after_damage_received", DAMAGE_CALCULATION: "damage_calculation" });
export const HELD_ITEM_DEFINITIONS = Object.freeze({
  oran: Object.freeze({ id: "oran", category: "held", activation: "conditional", trigger: HELD_ITEM_TRIGGER.AFTER_DAMAGE_RECEIVED, conditions: Object.freeze({ ownerAlive: true, hpRatioLTE: .5 }), effect: Object.freeze({ type: "heal_hp", percentMaxHp: .2 }), consumable: true }),
  sitrus: Object.freeze({ id: "sitrus", category: "held", activation: "conditional", trigger: HELD_ITEM_TRIGGER.AFTER_DAMAGE_RECEIVED, conditions: Object.freeze({ ownerAlive: true, hpRatioLTE: .5 }), effect: Object.freeze({ type: "heal_hp", percentMaxHp: .3 }), consumable: true }),
  "type-boost": Object.freeze({ id: "type-boost", category: "held", activation: "passive", trigger: HELD_ITEM_TRIGGER.DAMAGE_CALCULATION, conditions: Object.freeze({ moveMatchesPrimaryType: true }), effect: Object.freeze({ type: "damage_multiplier", multiplier: 1.1 }), consumable: false }),
});
const ABILITIES = { blaze: "fire", torrent: "water", overgrow: "grass" };
export const SUPPORTED_ABILITIES = Object.freeze({ blaze: "Com pouco HP, golpes Fire causam +20% de dano.", torrent: "Com pouco HP, golpes Water causam +20% de dano.", overgrow: "Com pouco HP, golpes Grass causam +20% de dano.", static: "Golpes físicos recebidos podem causar paralisia." });
export function getSupportedAbility(ability) { return SUPPORTED_ABILITIES[ability] ? { id: ability, description: SUPPORTED_ABILITIES[ability] } : null; }

// Compatibility export for old replays. New battles use getBattleMoves.
export const MOVES = [{ id: "strike", name: "Investida", type: "normal", power: 40, accuracy: 100, damageClass: "physical", special: false }, { id: "type-strike", name: "Golpe de tipo", type: "own", power: 70, accuracy: 100, damageClass: "special", special: true }];

const normalizeTypes = (value) => Array.isArray(value) ? value : Array.isArray(value?.types) ? value.types.map((type) => typeof type === "string" ? type : type.type?.name || type.name).filter(Boolean) : [value?.type || value].filter(Boolean);
const nextRandom = (state) => { const seed = ((state.rng || 123456789) * 1664525 + 1013904223) >>> 0; state.rng = seed; return seed / 4294967296; };
export function multiplier(attackType, defender) { return normalizeTypes(defender).reduce((total, defenseType) => total * (ADVANTAGES[attackType]?.includes(defenseType) ? DAMAGE_BALANCE.SUPER_EFFECTIVE : ADVANTAGES[defenseType]?.includes(attackType) ? DAMAGE_BALANCE.RESISTED : 1), 1); }
export function getTypeEffectiveness(attackType, defender) { return Math.min(DAMAGE_BALANCE.DOUBLE_WEAKNESS_CAP, multiplier(attackType, defender)); }
export function getOpponentWeaknesses(defender) { return Object.keys(ADVANTAGES).filter((attackType) => multiplier(attackType, defender) > 1); }
export function getPokemonMatchup(attacker, defender) { const factor = getTypeEffectiveness(normalizeTypes(attacker)[0] || "normal", defender); return factor > 1 ? "advantage" : factor < 1 ? "disadvantage" : "neutral"; }
export function getPotionHealAmount(pokemon) { return Math.min(Math.ceil(pokemon.maxHp * POTION_HEAL_PERCENTAGE), pokemon.maxHp - pokemon.hp); }
export function getHpRatio(currentHp, maxHp) { return maxHp > 0 ? Math.max(0, Math.min(1, currentHp / maxHp)) : 0; }
export function getBattleMoves(pokemon) { const type = normalizeTypes(pokemon)[0] || "normal"; const names = TYPE_MOVES[type] || TYPE_MOVES.normal; const status = STATUS_BY_TYPE[type]; return [{ id: type + "-quick", name: names[0], type, power: 40, accuracy: 100, damageClass: "physical", special: false, statusEffect: status ? { id: status, chance: .18 } : null }, { id: type + "-steady", name: names[1], type, power: 60, accuracy: 100, damageClass: "physical", special: false }, { id: type + "-special", name: names[2], type, power: 90, accuracy: 100, damageClass: "special", special: true, statusEffect: status ? { id: status, chance: .3 } : null }]; }

function prepareFighter(pokemon) { const types = normalizeTypes(pokemon); const base = pokemon.baseStats || {}; const maxHp = pokemon.maxHp || base.hp || 90; const stats = { attack: pokemon.stats?.attack || base.attack || 50, defense: pokemon.stats?.defense || base.defense || 50, specialAttack: pokemon.stats?.specialAttack || base.specialAttack || base.attack || 50, specialDefense: pokemon.stats?.specialDefense || base.specialDefense || base.defense || 50, speed: pokemon.stats?.speed || base.speed || 50 }; const defaults = getBattleMoves({ ...pokemon, types }); const custom = Array.isArray(pokemon.moveset) ? pokemon.moveset.filter((move) => move?.id && move?.power) : []; const moves = custom.length >= 3 ? custom.slice(0, 4) : [...defaults, ...custom.filter((move) => !defaults.some((defaultMove) => defaultMove.id === move.id))].slice(0, 4); return { ...pokemon, types, type: types[0] || "normal", hp: pokemon.hp ?? maxHp, maxHp, stats, moves, status: pokemon.status || null, heldItem: pokemon.heldItem || null, ability: pokemon.ability || null, specialAttackUsesRemaining: MAX_SPECIAL_ATTACK_USES, healsUsed: 0 }; }
function heldItemId(heldItem) { return heldItem?.endsWith?.("-boost") ? "type-boost" : heldItem?.toLowerCase?.() || null; }
export function resolveHeldItemEvent({ trigger, owner, targetPokemonId, sourcePokemonId = null, eventId = null, processedEventIds = [] }) {
  const itemId = heldItemId(owner?.heldItem); const definition = HELD_ITEM_DEFINITIONS[itemId];
  if (!definition || definition.trigger !== trigger || !owner || String(owner.id) !== String(targetPokemonId) || (eventId && processedEventIds.includes(eventId))) return null;
  if (definition.effect.type !== "heal_hp" || owner.hp <= 0 || getHpRatio(owner.hp, owner.maxHp) > definition.conditions.hpRatioLTE) return null;
  const beforeHp = owner.hp; const amount = Math.min(Math.ceil(owner.maxHp * definition.effect.percentMaxHp), owner.maxHp - owner.hp);
  if (amount <= 0) return null;
  owner.hp += amount;
  if (definition.consumable) owner.heldItem = null;
  return { type: "held-item-activated", itemId, pokemonId: owner.id, sourcePokemonId, targetPokemonId: owner.id, trigger, eventId, effect: { type: definition.effect.type, amount }, beforeHp, afterHp: owner.hp, consumed: definition.consumable };
}
// Compatibility helper for callers outside an action pipeline. It still requires
// the explicit post-damage event and cannot run from rendering or turn changes.
export function resolvePostDamageHeldItem(fighter) { return resolveHeldItemEvent({ trigger: HELD_ITEM_TRIGGER.AFTER_DAMAGE_RECEIVED, owner: fighter, targetPokemonId: fighter?.id }); }
function abilityBonus(fighter, type) { return ABILITIES[fighter.ability] === type && fighter.hp / fighter.maxHp <= 1 / 3 ? 1.2 : 1; }
export function getMovePowerFactor(power = 40, special = false) { const base = power <= 40 ? .15 : power <= 60 ? .18 : power <= 80 ? .21 : power <= 100 ? .24 : .27; return base * (special ? 1.25 : 1); }
export function calculateDamage({ attacker, defender, move, variance = 1 }) { const attackType = move.type === "own" ? attacker.type : move.type; const attack = move.damageClass === "special" ? attacker.stats.specialAttack : attacker.stats.attack; const defense = move.damageClass === "special" ? defender.stats.specialDefense : defender.stats.defense; const ratio = Math.min(DAMAGE_BALANCE.MAX_ATTACK_RATIO, Math.max(DAMAGE_BALANCE.MIN_ATTACK_RATIO, attack / Math.max(1, defense))); const levelFactor = Math.min(1.2, Math.max(.85, 1 + ((attacker.level || 1) - (defender.level || 1)) * .025)); const effectiveness = getTypeEffectiveness(attackType, defender); const stab = attacker.types.includes(attackType) ? DAMAGE_BALANCE.STAB : 1; const ability = abilityBonus(attacker, attackType); const held = heldItemId(attacker.heldItem) === "type-boost" && attacker.types?.[0] === attackType && attacker.heldItem === `${attacker.types[0]}-boost` ? HELD_ITEM_DEFINITIONS["type-boost"].effect.multiplier : 1; const special = Boolean(move.special); const minimum = special ? DAMAGE_BALANCE.SPECIAL_MIN : DAMAGE_BALANCE.REGULAR_MIN; const maximum = special ? DAMAGE_BALANCE.SPECIAL_MAX : DAMAGE_BALANCE.REGULAR_MAX; const percentage = Math.min(maximum, Math.max(minimum, getMovePowerFactor(move.power, special) * ratio * levelFactor * stab * effectiveness * ability * held * variance)); return { damage: Math.max(1, Math.round(defender.maxHp * percentage)), percentage, effectiveness, effectivenessLabel: effectiveness > 1 ? "super-effective" : effectiveness < 1 ? "resisted" : "neutral", stab: stab > 1, attackRatio: ratio, special, heldItemBonus: held > 1 ? { itemId: "type-boost", multiplier: held } : null }; }
function finishActorTurn(next, actor) { const fighter = next[actor].team[next[actor].active]; if (!fighter?.status || fighter.hp <= 0) return null; if (fighter.status.id === "burn" || fighter.status.id === "poison") { const damage = Math.max(1, Math.ceil(fighter.maxHp * STATUS_DAMAGE_PERCENTAGE)); fighter.hp = Math.max(0, fighter.hp - damage); return { status: fighter.status.id, damage }; } return null; }

export function createBattleState(host, guest, firstTurn) { const preparePlayer = (player) => { const bag = { potion: Math.max(0, Number(player.inventory?.potion ?? BATTLE_BAG.potion.quantity)), "full-heal": Math.max(0, Number(player.inventory?.["full-heal"] ?? BATTLE_BAG["full-heal"].quantity)) }; return { ...player, active: 0, bag, initialBag: { ...bag }, potionsRemaining: bag.potion, team: player.team.map(prepareFighter) }; }; const preparedHost = preparePlayer(host); const preparedGuest = preparePlayer(guest); const fasterGuest = (preparedGuest.team[0]?.stats.speed || 0) > (preparedHost.team[0]?.stats.speed || 0); return { host: preparedHost, guest: preparedGuest, turn: firstTurn || (fasterGuest ? "guest" : "host"), status: "playing", winner: null, log: "A batalha começou!", effect: null, rng: 123456789, resolvedItemEventIds: [], performance: { startedAt: null, endedAt: null, players: { host: { hasSwitched: false }, guest: { hasSwitched: false } } }, revision: 0 }; }

export function resolveAction(state, actor, action) {
  if (state.status !== "playing" || state.turn !== actor) return state;
  const enemy = actor === "host" ? "guest" : "host"; const next = structuredClone(state); const fighter = next[actor].team[next[actor].active];
  if (action.type === "switch") { if (!next[actor].team[action.index] || next[actor].team[action.index].hp <= 0 || action.index === next[actor].active) return state; next[actor].active = action.index; next.performance.players[actor].hasSwitched = true; next.turn = enemy; next.log = "Vai, " + next[actor].team[action.index].name + "!"; next.effect = { kind: "switch", actor }; next.revision += 1; return next; }
  if (action.type === "potion" || action.type === "item") { const itemId = action.type === "potion" ? "potion" : action.itemId; const quantity = itemId === "potion" ? Math.min(next[actor].bag?.potion ?? 0, next[actor].potionsRemaining ?? 0) : next[actor].bag?.[itemId] ?? 0; const targetIndex = next[actor].team.findIndex((pokemon) => String(pokemon.id) === String(action.targetPokemonId)); const target = next[actor].team[targetIndex]; if (!target || !quantity || target.hp <= 0 || (itemId === "potion" && (target.hp >= target.maxHp || target.healsUsed >= MAX_HEALS_PER_POKEMON)) || (itemId === "full-heal" && !target.status)) return state; const healing = itemId === "potion" ? getPotionHealAmount(target) : 0; const curedStatus = itemId === "full-heal" ? target.status?.id : null; if (itemId === "potion") { target.hp += healing; target.healsUsed += 1; } else target.status = null; next[actor].bag[itemId] = quantity - 1; next[actor].potionsRemaining = next[actor].bag.potion; next.turn = enemy; next.log = itemId === "potion" ? target.name + " recuperou " + healing + " HP!" : target.name + " foi curado!"; next.effect = itemId === "potion" ? { kind: "potion", actor, target: actor, targetPokemonId: target.id, targetIndex, healing, healsUsed: target.healsUsed, maxHeals: MAX_HEALS_PER_POKEMON } : { kind: "item", itemId, actor, target: actor, targetPokemonId: target.id, targetIndex, healing, curedStatus, remaining: next[actor].bag[itemId] }; next.revision += 1; return next; }
  const move = fighter.moves.find((item) => item.id === action.moveId) || MOVES.find((item) => item.id === action.moveId); const defender = next[enemy].team[next[enemy].active];
  if (!move || !defender || (move.special && fighter.specialAttackUsesRemaining <= 0)) return state;
  if (fighter.status?.id === "sleep") { fighter.status.turns -= 1; if (fighter.status.turns <= 0) fighter.status = null; next.turn = enemy; next.log = fighter.name + " está dormindo!"; next.effect = { kind: "status", actor, target: actor, status: "sleep" }; next.revision += 1; return next; }
  if (fighter.status?.id === "paralysis" && nextRandom(next) < .25) { next.turn = enemy; next.log = fighter.name + " está paralisado e não conseguiu agir!"; next.effect = { kind: "status", actor, target: actor, status: "paralysis" }; next.revision += 1; return next; }
  if (nextRandom(next) > (move.accuracy || 100) / 100) { next.turn = enemy; next.log = fighter.name + " errou " + move.name + "!"; next.effect = { kind: "miss", actor, target: enemy, type: move.type }; next.revision += 1; return next; }
  const attackType = move.type === "own" ? fighter.type : move.type; const resolution = calculateDamage({ attacker: fighter, defender, move, variance: 1 - DAMAGE_BALANCE.VARIANCE + nextRandom(next) * DAMAGE_BALANCE.VARIANCE * 2 }); const factor = resolution.effectiveness; const damage = resolution.damage;
  if (move.special) fighter.specialAttackUsesRemaining -= 1; defender.hp = Math.max(0, defender.hp - damage); let status = null; let reactiveAbility = null; if (!defender.status && move.statusEffect && nextRandom(next) < move.statusEffect.chance) { defender.status = { id: move.statusEffect.id, turns: move.statusEffect.id === "sleep" ? 2 : 0 }; status = defender.status.id; } if (!fighter.status && defender.ability === "static" && move.damageClass === "physical" && nextRandom(next) < .2) { fighter.status = { id: "paralysis", turns: 0 }; status = "paralysis"; reactiveAbility = "static"; }
  next.log = factor > 1 ? "SUPER EFETIVO!" : fighter.name + " usou " + move.name + "!"; next.effect = { kind: "attack", actor, target: enemy, type: attackType, damage, effective: factor > 1, special: move.special, moveName: move.name, status, ability: resolution.percentage > 0 && abilityBonus(fighter, attackType) > 1 ? fighter.ability : reactiveAbility, damageResolution: resolution, amplifier: resolution.heldItemBonus }; const damageEventId = action.actionId || `${actor}:${state.revision + 1}:${fighter.id}:${defender.id}:${move.id}`; const heldItem = resolveHeldItemEvent({ trigger: HELD_ITEM_TRIGGER.AFTER_DAMAGE_RECEIVED, owner: defender, targetPokemonId: defender.id, sourcePokemonId: fighter.id, eventId: damageEventId, processedEventIds: next.resolvedItemEventIds || [] }); if (heldItem) { next.effect.heldItem = { ...heldItem, owner: enemy, targetPlayerId: enemy }; next.resolvedItemEventIds = [...(next.resolvedItemEventIds || []), damageEventId].slice(-100); }
  if (defender.hp === 0) { const replacement = next[enemy].team.findIndex((pokemon) => pokemon.hp > 0); if (replacement === -1) { next.status = "finished"; next.winner = actor; next.performance.endedAt = Date.now(); next.log = defender.name + " desmaiou!"; } else { next[enemy].active = replacement; next.performance.players[enemy].hasSwitched = true; next.log = defender.name + " desmaiou! Vai, " + next[enemy].team[replacement].name + "!"; next.turn = enemy; } } else { const endStatus = finishActorTurn(next, actor); if (endStatus) next.effect.endStatus = endStatus; if (fighter.hp <= 0) { const replacement = next[actor].team.findIndex((pokemon) => pokemon.hp > 0); if (replacement === -1) { next.status = "finished"; next.winner = enemy; next.performance.endedAt = Date.now(); } else { next[actor].active = replacement; next.performance.players[actor].hasSwitched = true; } } if (next.status !== "finished") next.turn = enemy; }
  next.revision += 1; return next;
}
