"use client";
import { X } from "@phosphor-icons/react";
import { useEffect, useState } from "react";
import ItemDetailsModal from "@/components/ItemDetailsModal/ItemDetailsModal";
import ItemSprite from "@/components/ItemSprite/ItemSprite";
import { webStore } from "@/helpers/webStore";
import { EQUIPMENT_SLOT, getEquipableItemsForSlot, getHeldItemDefinition, getHeldItemStock } from "@/lib/economy/heldItems";
import styles from "./HeldItemDrawer.module.scss";

export default function HeldItemDrawer({ pokemon, economy, collection, heldItem, slot = EQUIPMENT_SLOT.STRATEGIC, open, onClose, onEquipped }) {
  const [snapshot, setSnapshot] = useState({ economy: economy || { inventory: {} }, collection: collection || [] }); const [detail, setDetail] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!open) return; Promise.all([webStore.getData("Pokedex"), webStore.getEconomy()]).then(([currentCollection, currentEconomy]) => setSnapshot({ collection: currentCollection, economy: currentEconomy })).catch(() => setError("Não foi possível carregar o inventário.")); }, [open, collection, economy]);
  if (!open) return null;
  const items = getEquipableItemsForSlot({ pokemon, slot }); const selected = detail && getHeldItemDefinition(detail); const stock = selected && getHeldItemStock({ economy: snapshot.economy, collection: snapshot.collection, itemId: selected.id });
  async function equip(id) { if (busy) return; setBusy(true); setError(""); try { const result = await webStore.setEquipmentItem(pokemon.id, id, slot); if (!result?.ok) { setError(result.reason === "TYPE_MISMATCH" ? "Esta relíquia não é compatível com o tipo deste Pokémon." : "Não foi possível equipar este item."); return; } setSnapshot({ collection: result.collection || snapshot.collection, economy: result.economy || snapshot.economy }); onEquipped(result.pokemon, "Equipamento atualizado.", result); setDetail(null); } finally { setBusy(false); } }
  return <div className={styles.backdrop} role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="held-title"><header><div><span>{slot === EQUIPMENT_SLOT.ELEMENTAL_RELIC ? "RELÍQUIA DE TIPO" : "ITEM ESTRATÉGICO"}</span><h2 id="held-title">Escolha um item</h2><p><b>EQUIPANDO EM</b> {pokemon.name}</p></div><button type="button" aria-label="Fechar seletor" onClick={onClose}><X size={21} /></button></header>{error && <p className={styles.error} role="alert">{error}</p>}{!items.length && <p className={styles.error}>Nenhuma relíquia compatível disponível.</p>}<div className={styles.grid}>{items.map((item) => { const itemStock = getHeldItemStock({ economy: snapshot.economy, collection: snapshot.collection, itemId: item.id }); const equipped = heldItem === item.id; const unavailable = !equipped && itemStock.available === 0; return <article key={item.id} className={`${styles.card} ${equipped ? styles.selected : ""} ${unavailable ? styles.empty : ""}`} role="button" tabIndex={0} onClick={() => setDetail(item.id)} onKeyDown={(event) => { if (event.key === "Enter") setDetail(item.id); }}><ItemSprite item={item.id} alt="" /><strong>{item.name}</strong><small>×{equipped ? itemStock.owned : itemStock.available}</small>{equipped && <em>✓ EQUIPADA</em>}<button type="button" disabled={busy || unavailable} onClick={(event) => { event.stopPropagation(); void equip(equipped ? null : item.id); }}>{equipped ? "DESEQUIPAR" : unavailable ? "×0" : "EQUIPAR"}</button></article>; })}</div>{selected && <ItemDetailsModal item={selected} quantity={stock.owned} available={stock.available} actionLabel={heldItem === selected.id ? "DESEQUIPAR" : "EQUIPAR"} actionDisabled={busy || (!stock.available && heldItem !== selected.id)} onAction={() => void equip(heldItem === selected.id ? null : selected.id)} onClose={() => setDetail(null)} />}</aside></div>;
}
